### ISSUE TITLE
first order

### ISSUE THREAD

**Issue by ValerkaKozlov** [amfauzn/Fantasia#13]
This nation have unique building - porta alchemica and it can only built in annexed sities. But I think this building must be able to build in all sities, not only in aannexed. Or Im wrong and first order military nation?

**Comment by amfauzn** [comment]
Hello, mate. Hope you a good day.
First Order is indeed a military civ that designed to capture a lot of cities to build it's UB (Porta Alchemica). The UB can only be built in annexed cities because it gave a strong (if not very strong) specialist slot with nice stat bonuses and high GS point.

**Comment by ValerkaKozlov** [comment]
Oh, thanks for the explanation
