### ISSUE TITLE
Mod errors?

### ISSUE THREAD

**Issue by Alucard0Reborn** [amfauzn/Fantasia#3]
Skeleton obsoletes at tech Domestication, and therefore Iron Working for its upgrade Swordsman may not yet be researched!
Caravel obsoletes at tech Combustion, and therefore Empowerment for its upgrade Ironclad may not yet be researched!
Privateer obsoletes at tech Combustion, and therefore Empowerment for its upgrade Ironclad may not yet be researched!
Ironclad obsoletes at tech Combustion, and therefore Combined Arms for its upgrade Destroyer may not yet be researched!

Unsure how to report this. I hit the auto fix and then gave me copy to clipboard.

**Comment by amfauzn** [comment]
Fixed!

**Comment by Alucard0Reborn** [comment]
Sweet! Dunno if I'm the only one reporting these but since one of you seem
active I've report all mod errors for all mods. I've been playing a lot of
UnCiv lately so maybe I'll be more active about this. Thank you for your
hard work!

**Comment by amfauzn** [comment]
What a dediccation you got there, anyway thanks for reporting this issue!
