### ISSUE TITLE
Clarification on beast tamers.

### ISSUE THREAD

**Issue by Malvisk** [amfauzn/Fantasia#4]
What units qualify to be tamed into a pet?

Is the chance to tame a beast only when the tamer attacks, or is there also the same chance if the tamer is attacked by a beast?

Thank you

**Comment by amfauzn** [comment]
it is when a tamer kill a beast.

the tips is to attack beast with either a hero and/or other military units, than use a tamer as finisher

**Comment by Malvisk** [comment]
Thank you!  That explains everything.
