### ISSUE TITLE
Allied city state destroying connecting railroads

### ISSUE THREAD

**Issue by Malvisk** [amfauzn/Fantasia#7]
I don't know if this behavior is from your mod or a previously unnoticed behavior from the base game or a new feature from the base game.

I'm allied with Chorislavia, they have an Elite Beast Tamer roaming my countryside, destroying railroads that are connecting my cities.  The places are in unclaimed land, but this keeps disconnecting my cities and hampering my war effort.

https://www.dropbox.com/s/jen6hgbhxis8vrh/%27Nkuhanea%20-%20ally%20prob.json?dl=0

**Comment by AceHank** [comment]
That is bug from base game. Since after 'Pillage Road' was introduced (version 4.3.4 ), there is a bug you mentioned. It applies to all unit for all civilization road/railroad outside border. The developers of Unciv are still working on it. You can track the problem in Unciv discord server.

**Comment by Malvisk** [comment]
Thank you, apologies for associating it to your mod.

**Comment by AceHank** [comment]
We don't mind. Please do report if you find another bug while playing the mod.

**Comment by amfauzn** [comment]
it is indeed base game bug, that nothing I can do about it. I'll fix it if there's solution for it tho

**Comment by amfauzn** [comment]
Close this as this behavior already fixed by itanasi (Unciv v4.3.9)
